### ISSUE TITLE
/tn Header links and embedded lists

### ISSUE THREAD

**Issue by CritchCode** [arnoudkooi/ServiceNow-Utils#286]
1. The header links (Scratchpad, Table fields and Toggle Label) don't show for embedded lists when using /tn the first time after a new record form loads but do show for embedded lists when following this sequence: /tn(on), /tn(off), /tn(on). The header links don't really have relevance for an embedded list, so likely shouldn't ever be shown there.

2. /tn doesn't show technical names for field headers within an embedded list on a form

SNUtils v6.1.2.1
Safari 15.3 (17612.4.9.1.8)

![SNUtils Embedded List behaviours](https://user-images.githubusercontent.com/55980966/185353482-aab4d490-93a2-4ce3-9dc1-6f8428bb4d1a.gif)

**Comment by arnoudkooi** [comment]
Thanks, I published a fix, will update when the Safari update is available.

**Comment by arnoudkooi** [comment]
The Safari update is published. Can you check?

**Comment by CritchCode** [comment]
Thanks Arnoud.

Issue 1 - still present - see gif.
Issue 2 - fixed.

SNUtils v6.1.2.8
Safari 15.3 (17612.4.9.1.8)

![Embedded list still showing on second tn](https://user-images.githubusercontent.com/55980966/185621057-9e62a4ad-bf33-4c72-960a-778de59ffbd2.gif)

**Comment by arnoudkooi** [comment]
This is what I see on first /tn trigger or with show tn on page load. Isn't this what is expected?

<img width="734" alt="image" src="https://user-images.githubusercontent.com/840781/185623141-56222eb8-836c-459f-8168-31148b5996bc.png">

**Comment by CritchCode** [comment]
Your screenshot is what I'd expect for a scripted relationship, yes. However, what you're actually looking at there in that example is a Formatter, containing a UI Macro, which calls a function to then render an embedded list. So while it works ok for you, it's not a great match for the issue I've seen.

My example is the 'Special Handling Notes List' which is a scripted relationship that's been added to the incident form. (comes with the com.sn_shn plugin) - but it's just a normal scripted relation added to a form via form layout.

I have verified that the issue also occurs with a reference related list (Task SLAs) being added as an embedded list to a form, rather than adding a scripted relation as an embedded list - see below...

First /tn...
![image](https://user-images.githubusercontent.com/55980966/185657546-176b1fd6-6796-4554-a195-9722ef28883d.png)

Then after turning /tn off and then on again...
![image](https://user-images.githubusercontent.com/55980966/185659619-08537eed-2e78-41d7-99e1-f2e0619a663a.png)

Not a major issue by any stretch of the imagination, but something I spotted, so wanted to report.

**Comment by arnoudkooi** [comment]
I can check if you provide a PDI where the issue occurs.

**Comment by CritchCode** [comment]
Thanks, I just spun a fresh one up.

https://dev89767.service-now.com
arnoud_the_legend
$wFz@o&Vsyo-lN<8FR9Ey
admin and sec_admin

Take a look at the notes section of the incident form where I've added those two embedded lists as above

**Comment by arnoudkooi** [comment]
Ill update when the new fix is available for Safari. I removed the credntilas from the comment, altough I did like the login you choose ;)

<img width="395" alt="image" src="https://user-images.githubusercontent.com/840781/185688542-4323965a-4b31-4ae0-a9f4-7b5a6a3c71a9.png">

**Comment by arnoudkooi** [comment]
The 6.1.2.9 is now available. Please check.
