### ISSUE TITLE
Cannot /tn on instance options on portal (Floorp/Firefox ESR)

### ISSUE THREAD

**Issue by Zorakie** [arnoudkooi/ServiceNow-Utils#513]
Hi, this is probably not an issue for the majority, but I have noticed this issue in my Floorp browser, which is based on Firefox ESR.

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/14437576/6cf4217c-8a21-4aa7-af34-4a98ec62cf04)

When I open the widget's instance options and I hit /tn (to show the technical names of the options that were configured on the widget), I get an error above. When I try this in my Firefox for Developers, it works just fine. I have SNUtils OnPrem in the latest version (8.1.3.1) on both browsers. 

At this point, it can be anything, maybe some issue with Firefox ESR, maybe some Floorp setting, but I haven't seen any cross-origin related hardening settings in Floorp.

There are though some differences in about:config...

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/14437576/930ed750-c153-479f-a078-b2bb4a0995f4)

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/14437576/6abf3b24-2528-4bda-8122-d353ded914e1)

Any idea, what could be causing this?

Thank you!

**Comment by arnoudkooi** [comment]
Is something loaded from a different instance, maybe?

**Comment by Zorakie** [comment]
Nothing I would know of. It is pretty much just our custom widget on a fresh new page. And as mentioned. If I open exactly the same thing in Firefox Dev, it works just fine 🤷‍♂️.

**Comment by arnoudkooi** [comment]
I tried with Floorp and could not repicate, do you see it on all portals/instances?

**Comment by Zorakie** [comment]
Unfortunately, yes. I tried also on my second computer to put specific device out of the equation, I tried a totally different instance (different vendor), and the same issue. 
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/14437576/b12030d5-fc30-45eb-929c-ae482a56e9ea)

**Comment by arnoudkooi** [comment]
Do you have exact steps to reproduce? 
There is no extension adding an iframe from a cross scope source?

**Comment by Zorakie** [comment]
1) log in to the instance
2) Go to portal, e.g. /sp
3) CTRL+ right click any widget -> Instance options
4) While the modal with instance options is shown do /tn on your keyboard, confirm by enter and check the error in your console.


No plugin that I would be aware of.
In both Firefox for DEV and Floorp, I have the same set of plugins as I was migrating to Floorp recently.
SNUtils,
UBlock
Bitwarden password manager
Privacy Badger

**Comment by arnoudkooi** [comment]
Maybe you can paste below in console and see if you can debug, maybe there is an iframe with a weird source?

```javascript
var iframes = window.top.document.querySelectorAll("iframe");
iframes.forEach((iframe) => {
	//debugger;
	console.log(iframe);
  if (typeof iframe.contentWindow.snuAddTechnicalNames != 'undefined')
    iframe.contentWindow.snuAddTechnicalNames();
});
```

**Comment by Zorakie** [comment]
Ok, got it ... I have no idea, what has happened but I can confirm the following:

1) The second instance I tried, was apparently a fluke, after a few reloads, when I tried your snippet, it just started working. I tried even third, completely different instance, and it was working just fine.
2) On the first instance, there is indeed one extra iframe. So apparently, someone has installed a 3rd party cookie policy library, and for some reason, even if I have rejected the cookies in both browsers, in Firefox, this iframe no longer loads, but is still present in Floorp (so maybe some localstorage or cookie issue).

Anyway, considering there could be some 3rd party libraries adding such iframes, would that be possible to add some try/catch for your snuAddTechnicalNames method?

**Comment by arnoudkooi** [comment]
I'll add below in next update, think that should fix it

```javascript
    try {
        if (typeof iframe.contentWindow.snuAddTechnicalNames != 'undefined')
            iframe.contentWindow.snuAddTechnicalNames();
    } catch (e) { } //ignore cross-origin frames
```

**Comment by arnoudkooi** [comment]
Did the latest update resolve the issue?

**Comment by Zorakie** [comment]
YES! 🥳

I can confirm that: If I run the code from above, it still shows that iframe and crashes on that iframe.
But SNUTILS now correctly shows the technical names and no crashes observed.

Thank you very much!!!!
